#oracle properties
oracle:
 datasource:
  driver-class-name: oracle.jdbc.driver.OracleDriver
  jdbc-url: jdbc:oracle:thin:@localhost:1521:orcl
  username: siva
  password: velpula
  
#mySql props
mysql:
 datasource:
  driverClassName: com.mysql.cj.jdbc.Driver
  jdbc-url: jdbc:mysql:///springboot
  username: root
  password: siva