#oracle propertiees
oracle:
 datasource:
  driver-class-name: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521:orcl
  username: siva
  password: velpula
 
 
#Mysql properties
mysql:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.driver
  url: jdbc:mysql:///siva1
  username: siva
  password: siva
  
